### ISSUE TITLE
Process check

### ISSUE THREAD

**Issue by russel** [Zipios/Zipios#11]
I had assumed we were using a pull request process rather than a direct commit process. However no-one has checked and committed my pull requests and Alexis is committing direct. If we are using a committing direct process I will commit my own pull requests and change my process.

**Comment by AlexisWilke** [comment]
Sorry, I wasn't sure what you meant by a pull request. People directly accessing the git repository should expect the latest and it seems that I saw your pull requests in the latest... I don't think this is such a large project that pull requests would be required.

**Comment by russel** [comment]
I can work with a process not using pull requests, not a problem.
