### ISSUE TITLE
License Discrepancy

### ISSUE THREAD

**Issue by harmic** [Zipios/Zipios#28]
The main COPYING file in the root directory specifies the LGPL.

However there are source code files src/dostime.h and src/dostime.c which have a comment at the top stating the licence for those files is GPL2+. dostime.h is included from a number of source files.

Doesn't that mean that the whole thing has to be licenced GPL? If not why not?

My reason for asking: zipios would be ideal for use in a work project. We can use LGPL libraries but not GPL.

**Comment by AlexisWilke** [comment]
Hmmm... Good point. These two dostime files come from _really_ old code picked to support the MS-DOS FAT file system dates. I tweaked these functions quite a bit (to have real error checking) so I suppose I could change the license to be LGPL. I'm checking to see how viable this is. I could also change it to use C++ only that way it's also a different language and less prone to old copyright holders. I should have a better answer in a few days.

**Comment by AlexisWilke** [comment]
Okay, I replaced those two files with my own using a C++ class. I tried not to change the rest of the code so it should be the same interface. I don't guarantee that 100% though. I updated the dosdatetime.cpp test to run against the new code and updated everything to use the C++ class. All the tests pass so I would think we're all good (some tests make use of the output of `zip` and they returned the correct date and time.)

So we should be A-Okay with LGPL now. Thanks again for pointing that out!

It's getting late here, but I should have a new package on [Launchpad](https://launchpad.net/~snapcpp/+archive/ubuntu/ppa/+packages) ready within a day or two.

**Comment by dooglio** [comment]
@AlexisWilke a good idea is to submit a PR with the change, and add "closes #28" to the text. Plus if you ask me for a review, I can look it over.

**Comment by AlexisWilke** [comment]
@dooglio I guess I forgot to put #28 in the commit comments...

The new file is here:

https://github.com/Zipios/Zipios/blob/master/src/dosdatetime.cpp

There is a link near the top to the Microsoft doc in link with the FAT date.

The main changes are here for this request, although it includes a few other clean ups:

https://github.com/Zipios/Zipios/commit/dfb9fed89d692539c1878423800b73ea46554eac#diff-25d902c24283ab8cfbac54dfa101ad31

**Comment by dooglio** [comment]
@AlexisWilke I added comments to the commit itself. In the future, I'd like a pull request.

**Comment by AlexisWilke** [comment]
Okay, I was able to run the coverage test and extended it to 100% for the new DOS Date & Time. I found and fixed one bug in the process.

**Comment by AlexisWilke** [comment]
Okay, the new Debian package (Ubuntu 16.04) is now available here: https://launchpad.net/~snapcpp/+archive/ubuntu/ppa/+packages
