### ISSUE TITLE
Make repositories consistent

### ISSUE THREAD

**Issue by russel** [Zipios/Zipios#3]
I tried to push the Git repository to Sourceforge, but Sourceforge refuses traffic on port 22. The Sourceforge repository is a couple of changesets behind the one here. It seems that the project is caught half on Sourceforge, half on GitHub. My belief is that we should complete the move to GitHub and remove everything that we can from Sourceforge and direct everyone from there to here.

**Comment by AlexisWilke** [comment]
I never tried git at Sourceforge...

If I'm correct we can delete all the files published on sourceforge, but probably not the repository. That is, I don't recall anything about being able to do such.

And I do not know of a good way to let people know that the repository moved (we posted messages, I'm sure, but that's something many people do not read before trying / testing for a while, wasting their time with the wrong stuff.)

**Comment by russel** [comment]
I'll see what I can delete at Sourceforge and try harder to redirect people here.

**Comment by AlexisWilke** [comment]
Note that I changed the description to ask people to come here.

However, the Sourceforge.net repository has version 1.x which we may want to keep available so people can still have a backward compatible version of the library...
