### ISSUE TITLE
zipios 2.2.5.0 produces different documentation on different architectures

### ISSUE THREAD

**Issue by hobbes1069** [Zipios/Zipios#33]
As a common practice, non-arch specific content is shared across packages in Fedora/RPM.

On Fedora I package a zipios-doc subpackage but when attempting to build 2.2.5.0 I get different output, sometimes on ppc64le and sometimes on s390x but the error is the same:

```
BuildError: The following noarch package built differently on different architectures: zipios-doc-2.2.5.0-1.fc33.noarch.rpm
rpmdiff output was:
removed     /usr/share/doc/zipios/html/dir_0f7abfb91da657dcb27dff31b827312f.html
removed     /usr/share/doc/zipios/html/dir_32504400af4b8c553a85c61a7ef01dea.html
added       /usr/share/doc/zipios/html/dir_8f6b9ad7431774f92e3ec3efe35ac7da.html
added       /usr/share/doc/zipios/html/dir_dd208edd458824e9eaf902c6da16200d.html
```

I haven't had time to dig into why different directory names would be produced on different architectures but any tips would be appreciated.

**Comment by AlexisWilke** [comment]
The HTML directory is generated using doxygen. I don't really have any control over that. I don't know what they use. An MD5, or maybe time, a random number?

**Comment by hobbes1069** [comment]
I don't think it's random, it seems consistent but only on ppc64le and s390x... I'll dig in a bit more.

**Comment by hobbes1069** [comment]
Which after I let that thought settle in my head for a bit... Aren't s390 and ppc64 both big endian architectures?

**Comment by hobbes1069** [comment]
As a complete SWAG I tried this, it got rid of one of the directory problems but one remains.

```
Index: doc/zipios.doxy.in
===================================================================
--- Zipios/doc.orig/zipios.doxy.in
+++ Zipios/doc/zipios.doxy.in
@@ -152,7 +152,7 @@ FULL_PATH_NAMES        = YES
 # will be relative from the directory where doxygen is started.
 # This tag requires that the tag FULL_PATH_NAMES is set to YES.
 
-STRIP_FROM_PATH        = @CMAKE_CURRENT_SOURCE_DIR@
+STRIP_FROM_PATH        = @CMAKE_CURRENT_BINARY_DIR@
 
 # The STRIP_FROM_INC_PATH tag can be used to strip a user-defined part of the
 # path mentioned in the documentation of a class, which tells the reader which
```

From what I understand multiple paths can be set but I couldn't find an example. Are they space separated? comma? semicolon?

**Comment by hobbes1069** [comment]
Gave up and forced the build directory to be the same for all arches.

**Comment by AlexisWilke** [comment]
The HTML directory is generated using doxygen. I don't really have any control over that. I don't know what they use. An MD5, or maybe time, a random number?
