### ISSUE TITLE
Failing tests on i386 platform

### ISSUE THREAD

**Issue by mzf-guest** [Zipios/Zipios#36]
Some DirectoryEntry tests and DOSDateTime tests are failing on i386 platform.

It seems that the generated time given to `zipios::DOSDateTime::setUnixTimestamp` is out of the limits. So maybe the tests should be updated for 32bits platforms?

Test output:

```
/usr/bin/ctest --force-new-ctest-process -j1
Test project /builds/debian/zipios/debian/output/source_dir/obj-i686-linux-gnu
    Start 1: zipios_tests
1/1 Test #1: zipios_tests .....................***Failed  173.81 sec
zipios_tests[16787]: version 2.2.0, seed is 1601497941
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
zipios_tests is a Catch v1.12.1 host application.
Run with -? for options
-------------------------------------------------------------------------------
DirectoryEntry with one valid file
-------------------------------------------------------------------------------
/builds/debian/zipios/debian/output/source_dir/tests/directoryentry.cpp:745
...............................................................................
/builds/debian/zipios/debian/output/source_dir/tests/directoryentry.cpp:1011: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  Year out of range for an MS-DOS Date & Time object. Range is [1980, 2107].
-------------------------------------------------------------------------------
Scenario: DirectoryEntry for a valid directory
     Given: test an existing directory and no comment
      When: setting the DOS time
-------------------------------------------------------------------------------
/builds/debian/zipios/debian/output/source_dir/tests/directoryentry.cpp:1664
...............................................................................
/builds/debian/zipios/debian/output/source_dir/tests/directoryentry.cpp:1664: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  Year out of range for an MS-DOS Date & Time object. Range is [1980, 2107].
warning: Unix to DOS time conversion is ignored on platform with a 32 bit time_t definition.
warning: Unix to DOS time conversion is ignored on platform with a 32 bit time_t definition.
-------------------------------------------------------------------------------
Random DOS Date & Time
  more random tests
-------------------------------------------------------------------------------
/builds/debian/zipios/debian/output/source_dir/tests/dosdatetime.cpp:464
...............................................................................
/builds/debian/zipios/debian/output/source_dir/tests/dosdatetime.cpp:476: FAILED:
  REQUIRE_THROWS_AS( td.setUnixTimestamp(t), zipios::InvalidException & )
because no exception was thrown where one was expected:
===============================================================================
test cases:      35 |      32 passed | 3 failed
assertions: 1668035 | 1668032 passed | 3 failed
0% tests passed, 1 tests failed out of 1
Total Test time (real) = 173.81 sec
The following tests FAILED:
	  1 - zipios_tests (Failed)
Errors while running CTest
```

Thanks,

**Comment by mzf-guest** [comment]
I've investigated the failure, it seems that `std::time_t` is implemented by a 32bit signed integer by GCC on x86 platform, but the zipios est code expects an unsigned integral value.

Hence the static cast from unsigned integral type `std::size_t` to signed integral type `std::time_t` may create negative values that gives incorrect result for a time representation. 

For example in [tests/directoryentry.cpp line 1150](https://github.com/Zipios/Zipios/blob/45c468faefe900ac051be1daa05afa9e5424af05/tests/directoryentry.cpp#L1150):
```cpp
std::time_t t(static_cast<std::time_t>(zipios_test::rand_size_t()) % (4354848000LL - 315561600LL) + 315561600);
```
In the failing test, `t` is assigned to -1849345661 value that makes the `zipios::DOSDateTime::setUnixTimestamp` fails.

Similarly, in `tests/dosdatetime.cpp`, call to [`mktime`](https://github.com/Zipios/Zipios/blob/45c468faefe900ac051be1daa05afa9e5424af05/tests/dosdatetime.cpp#L91) fails and set  `g_maximum_unix` to -1 value. Then the [t > g_maximum_unix](https://github.com/Zipios/Zipios/blob/45c468faefe900ac051be1daa05afa9e5424af05/tests/dosdatetime.cpp#L473) test is meaningless and makes the following line fails.

I'll try to create a fix.

**Comment by AlexisWilke** [comment]
Yes. Some of the tests for time are 64 bit specific as the dates in a zip file can go beyond the dates in a `time_t` variable when running in 32 bits.

I've done updates to avoid running those tests in 32 bits. You should not see errors anymore.

Let me know whether you still see errors.

Thank you for your patience.

**Comment by mzf-guest** [comment]
I've tried your modifications and no more errors.
Thanks for being always responsive!

Could you please tag a new version with your modifications?

**Comment by AlexisWilke** [comment]
Here:
https://github.com/Zipios/Zipios/releases/tag/2.2.6

**Comment by mzf-guest** [comment]
Thanks!
