### ISSUE TITLE
Invalid char in metadata?

### ISSUE THREAD

**Issue by waebbl** [Zipios/Zipios#40]
There seems to be an invalid char in https://github.com/Zipios/Zipios/blob/master/contrib/zipios.metainfo.xml.in#L8 as last char on the line (reverse question mark from spanish language)
It looks like the file isn't properly utf-8 encoded too, the `ö` in the second line in `Glöckner` is shown as `<F6>` on my linux box.

**Comment by AlexisWilke** [comment]
Not too sure where that reversed question mark is from... I fixed the source and pushed the change.  
Thank you.
