### ISSUE TITLE
Segfault in zipios_example on wrong filename

### ISSUE THREAD

**Issue by alochmann** [Zipios/Zipios#42]
Not a bug in zipios, but in zipios_example.cpp, line 75: If zipios_example is called with an existing zip-file but wrong filename to extract, zipios_example will segfault here. An error message with ent->getName() should be shown, but ent is null. Should be argv[2] instead of ent->getName().

**Comment by AlexisWilke** [comment]
Thank you for reporting that issue! I made an update.
