### ISSUE TITLE
Missing release for current code

### ISSUE THREAD

**Issue by StefanBruens** [Zipios/Zipios#45]
The repository has seen quite some changes since the 2.2.6 release, including critical ones like the CRC fixes.

A current release would be welcome for inclusion in various distributions.

**Comment by StefanBruens** [comment]
[![Packaging status](https://repology.org/badge/vertical-allrepos/zipios.svg?exclude_unsupported=1&columns=6)](https://repology.org/project/zipios/versions)

**Comment by AlexisWilke** [comment]
Indeed. I'm not taking as much care as I should about those...

https://github.com/Zipios/Zipios/releases/tag/2.3.2

Thank you for pointing that out.
